baseurl = "http://www.610yesnolovely.org/moysetutoring/"
languageCode = "en-us"
title = "Moyse Tutoring"
theme = "hugo-strata-theme"

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Su Thompson"
	description = "Moyse Tutoring at Kitsalno, Vancouver, BC, Canada."

	# Enable Google Analytics by inserting your tracking code
	googleAnalytics = ""


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "SuHeadshot.jpeg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = """

*“We are exploring together. We are cultivating a garden together,
 backs to the sun. The question is a hoe in our hands and we are
 digging beneath the hard and crusty surface to the rich humus of our
 lives.”* - Parker J. Palmer

"""
		# The icons will be shown if you enter your username
		twitter = ""
		github = ""
		dribbble = ""

		copyright = [
			"&copy; 2015 Su Thompson",
			"Powered by: [Hugo](https://gohugo.io) - Design by: [HTML5 UP](//html5up.net)"
		]


	[params.about]
		title = "Moyse Tutoring"
		content = """
Private tutoring is a growing endeavour in Vancouver: many high school
and college students benefit from extra tuition. It may be that they
struggle with a particular subject or have a demanding project to
complete; or that they are preparing for further education, or need
help composing an essay.  Some need a couple of sessions, some require
many more. But all need a skilled tutor who will come alongside them,
to help them through.

Moyse Tutoring will offer after school, Saturday and school holiday
tutoring, for one or two students at a time, at the company’s tutoring
room located in the Kitsilano/Granville Island neighbourhood. Both
English and Social Studies will be offered. Moyse Tutoring is a sole
proprietorship owned and operated by Su Thompson.
"""

	[params.portfolio]
		title = "Recent Work"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/01.jpg"
			thumb = "thumbs/01.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/03.jpg"
			thumb = "thumbs/03.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/04.jpg"
			thumb = "thumbs/04.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/05.jpg"
			thumb = "thumbs/05.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/06.jpg"
			thumb = "thumbs/06.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."


	[params.contact]
		title = "Get In Touch"
		content = "Feel free ask questions by email, phone or sending a message."

		address = [
			"Address Line 1.",
			"Kitsalano, Vancouver, BC",
			"VXX XXX",
			"Canada"
		]
		address_url = "https://www.google.ca/maps/place/2183+Fir+St,+Vancouver,+BC+V6J+3B5/@49.2663716,-123.1414656,19z/data=!3m1!4b1!4m2!3m1!1s0x548673c86913cabf:0x6d6e32e95fbf4eba"
		phone = "604-757-2596"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "moysetutoring@icloud.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"