baseurl = "http://www.moysetutoring.ca/"
languageCode = "en-us"
title = "Moyse Tutoring"
theme = "hugo-strata-theme"

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Su Thompson"
	description = "Moyse Tutoring at Kitsalno, Vancouver, BC, Canada."

	# Enable Google Analytics by inserting your tracking code
	googleAnalytics = ""


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "SuHeadshot.jpg"
		bio = ""
		
		# The icons will be shown if you enter your username
		twitter = ""
		github = ""
		dribbble = ""

		copyright = [
			"&copy; 2015 Su Thompson",
			"Powered by: [Hugo](https://gohugo.io) - Design by: [HTML5 UP](//html5up.net)"
		]


	[params.about]
		title = ""
		content = ""

	[params.portfolio]
		title = "Recent Work"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/01.jpg"
			thumb = "thumbs/01.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/03.jpg"
			thumb = "thumbs/03.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/04.jpg"
			thumb = "thumbs/04.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/05.jpg"
			thumb = "thumbs/05.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/06.jpg"
			thumb = "thumbs/06.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."


	[params.contact]
		title = "Get In Touch"
		content = "Feel free ask questions by email, phone or sending a message."

		address = [
			"211 - 2628 Granville Street",
			"Vancouver",
			"BC",
			"V6H 4B4",
			"Canada"
		]
		address_url = "https://www.google.ca/maps/place/2628+Granville+St,+Vancouver,+BC+V6H+3H8/@49.2622092,-123.1406226,17z/data=!3m1!4b1!4m2!3m1!1s0x548673c761de1ee1:0xc646300b0c1516de"
		phone = "604-757-2596"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "moysetutoring@icloud.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"
