#!/bin/bash

usage()
{
    echo "usage: pages-export in.pages out.docx" >&2
    exit 1
}

if [[ $# -ne 2 ]]; then
    usage
fi

input="$1"
output="$2"

if [[ ! "$input" =~ .pages$ ]]; then
    usage
fi

if [[ ! "$output" =~ .docx$ ]]; then
    usage
fi

if [[ "$input" =~ ^[^/] ]]; then
    input="$PWD/$input"
fi

if [[ "$output" =~ ^[^/] ]]; then
    output="$PWD/$output"
fi

echo -e "Converting \"$input\" to \"$output\" ... \c"
osascript pages-export.as "$input" "$output"
echo "Done"
exit 0
